services:
  postgres:
    image: postgres:latest
    container_name: paytm-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
